import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hisdemo1.doctor9.com/SUVARNA_HIS/Default.aspx');
  await page.locator('#txtUserName').fill('mvr');
  await page.locator('#txtUserName').press('Tab');
  await page.locator('#txtPassword').fill('S$1234');
  await page.locator('#txtPassword').press('Enter');
  await page.locator('#ddlUserLocation').press('ArrowDown');
  await page.locator('#ddlUserLocation').selectOption('1');
  await page.locator('#ddlUserLocation').press('Tab');
  await page.getByRole('button', { name: 'Continue' }).press('Enter');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'X' }).click();
  await page.locator('.module-icon.Module-16').click();
  await page.getByText('Registration').first().click();
  await page.locator('#li_18').getByText('Registration', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter First Name' }).click();
  await page.getByRole('textbox', { name: 'Enter First Name' }).fill('basha');
  await page.getByRole('textbox', { name: 'Enter First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Receipt # Receipt Dt Cash Amt' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Last Name' }).fill('s');
  await page.getByRole('textbox', { name: 'Enter Last Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'DD-MM-YYYY' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter the age in years' }).fill('25');
  await page.getByRole('textbox', { name: 'Enter the age in years' }).press('Tab');
  await page.locator('#ctl00_ContentPlaceHolder1_ddlMaritalStatus').selectOption('1');
  await page.locator('#ctl00_ContentPlaceHolder1_ddlquestionary').selectOption('3');
  await page.locator('#lk_btn_ctl00_ContentPlaceHolder1_ucConsultant').click();
  await page.locator('#progress > .cmask').click();
  await page.getByRole('textbox', { name: 'Enter Mobile Number1' }).fill('8979879871');
  await page.getByRole('textbox', { name: 'Enter Address1' }).fill('3234234');
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('textbox', { name: 'Search For Document' }).press('Alt+s');
  const page2 = await page2Promise;
  const page4Promise = page.waitForEvent('popup');
  await page.goto('https://hisdemo1.doctor9.com/SUVARNA_HIS/private/frontoffice/YRegistration.aspx?encrypt=1&Type=UmVn&DOC_FORM_CD=UkVHLUVYUElSWQ==');
  const page4 = await page4Promise;
});